name: OWASP ZAP Scan

on:
  workflow_run:
    workflows: ["Docker Image CI"] # Triggers after the Docker Image CI workflow
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Create Docker Network
        run: docker network create zap-network

      - name: Start Application
        run: |
          echo "Docker User: ${secrets.DOCKER_USER}"
          docker run --network zap-network -e ASPNETCORE_ENVIRONMENT=Development -d -p 5000:5000 ${secrets.DOCKER_USER}/userservice:latest

      - name: Verify Application is Running
        run: |
          curl http://localhost:5000 || (echo "Application not running!" && exit 1)

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:5000'
          cmd_options: '-a'
